# Generated by Django 5.2.7 on 2025-11-08 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=512)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=64)),
                ('object_repr', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('create', 'Crear'),
                 ('update', 'Actualizar'), ('delete', 'Eliminar')], max_length=10)),
                ('changes', models.TextField(blank=True, null=True)),
                ('extra', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['app_label', 'model'], name='auditoria_a_app_lab_a0297d_idx'), models.Index(fields=['object_id'], name='auditoria_a_object__9aaba1_idx'), models.Index(fields=['action'], name='auditoria_a_action_11716b_idx'), models.Index(fields=['timestamp'], name='auditoria_a_timesta_78f4a2_idx')],
            },
        ),
    ]
