
[pytest]
DJANGO_SETTINGS_MODULE = proyec_imprenta.imprenta_tucan.impre_tucan.settings
python_files = tests.py test_*.py *_tests.py

addopts = --tb=short -p proyec_imprenta.imprenta_tucan.pytest_vscode_style
