# Generated by Django 5.2.7 on 2025-10-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('fechaRegistro', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clientes_cliente',
            },
        ),
    ]
