# Generated by Django 5.2.7 on 2025-10-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fechaRegistro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='idCliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(default='Sin ciudad', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')],
                                   default='Activo', max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(default='Argentina', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(default='Misiones', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='cliente',
            table=None,
        ),
    ]
