# Generated by Django 5.2.7 on 2025-10-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(choices=[('Posadas', 'Posadas'), ('Eldorado', 'Eldorado'),
                                   ('Oberá', 'Oberá')], default='Posadas', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(choices=[('Misiones', 'Misiones'), ('Buenos Aires',
                                   'Buenos Aires'), ('CABA', 'CABA')], default='Misiones', max_length=100),
        ),
    ]
