# Generated by Django 5.2.7 on 2025-11-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_ciudad_alter_cliente_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(default='Posadas', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(default='Misiones', max_length=100),
        ),
    ]
