# Generated by Django 5.2.7 on 2025-11-08 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_ciudad_alter_cliente_provincia'),
    ]

    operations = [
        # Migration intentionally left blank: reverted FK change.
    ]
