# Generated by Django 5.2.7 on 2026-02-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_rename_columns_physical'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_ultima_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='puntaje_estrategico',
            field=models.FloatField(default=0),
        ),
    ]
