# Generated by Django 6.0.2 on 2026-02-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_cliente_fecha_ultima_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cuit',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
