# Generated by Django 6.0.2 on 2026-02-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_cliente_cuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuit',
            field=models.CharField(default='00000000000', max_length=11, unique=True, verbose_name='CUIT'),
        ),
    ]
