# Generated by Django 6.0.2 on 2026-02-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_alter_cliente_cuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('premium', 'Premium'), ('estrategico', 'Estratégico'), ('estandar', 'Estándar'), ('nuevo', 'Nuevo')], default='nuevo', max_length=15, verbose_name='Tipo de Cliente'),
        ),
    ]
