# Generated by Django 6.0.2 on 2026-03-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_cliente_telefono_e164_cliente_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email_verificado',
            field=models.BooleanField(default=False, help_text='Indica si el email del cliente fue verificado y es valido para envios'),
        ),
    ]
