# Generated by Django 6.0.2 on 2026-04-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_cliente_email_verificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuit',
            field=models.CharField(blank=True, default='', max_length=11, unique=True, verbose_name='CUIT'),
        ),
    ]
