# Generated by Django 6.0.2 on 2026-04-11 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_cuit_default_vacio'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad_fk',
            field=models.ForeignKey(blank=True, help_text='Referencia a la tabla de ciudades. Cuando está completo, tiene prioridad sobre el campo texto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='geo.ciudad', verbose_name='Ciudad (normalizado)'),
        ),
    ]
