# Generated by Django 5.2.7 on 2026-03-29 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0015_cliente_email_verificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='ID de sesión para usuarios sin login', max_length=100)),
                ('mensaje', models.TextField()),
                ('respuesta', models.TextField()),
                ('es_cliente', models.BooleanField(default=True, help_text='True si es mensaje del cliente, False si es del bot')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_chatbot', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Conversación Chatbot',
                'verbose_name_plural': 'Conversaciones Chatbot',
                'ordering': ['-fecha'],
            },
        ),
    ]
