# Generated by Django 6.0.2 on 2026-04-11 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionchatbot',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario interno (staff) que inició la conversación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_chatbot', to=settings.AUTH_USER_MODEL),
        ),
    ]
