# Generated by Django 5.2.7 on 2025-10-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin nombre', max_length=100)),
                ('descripcion', models.TextField()),
                ('modulo', models.CharField(max_length=100)),
                ('acciones', models.TextField(default='[]')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'),
                 ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
        ),
    ]
