# Generated by Django 5.2.7 on 2025-11-23 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0002_auto_20251122_1732'),
        ('insumos', '0002_insumo_cantidad_insumo_precio_unitario_and_more'),
        ('pedidos', '0001_initial'),
        ('proveedores', '0006_alter_proveedorparametro_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRecomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('aceptar', 'Aceptar'),
                 ('modificar', 'Modificar'), ('rechazar', 'Rechazar')], max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('feedback_precio', models.FloatField(default=0)),
                ('feedback_cumplimiento', models.FloatField(default=0)),
                ('feedback_incidencias', models.FloatField(default=0)),
                ('feedback_disponibilidad', models.FloatField(default=0)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.insumo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
                ('proveedor_final', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='feedback_final', to='proveedores.proveedor')),
                ('proveedor_recomendado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='feedback_recomendado', to='proveedores.proveedor')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
