# Generated by Django 5.2.7 on 2026-02-07 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0003_feedbackrecomendacion'),
        ('clientes', '0009_cliente_fecha_ultima_actualizacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaPropuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('descuento', 'Descuento'), ('fidelizacion', 'Fidelización'), ('prioridad_stock', 'Prioridad en stock')], max_length=30)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('enviada', 'Enviada al cliente'), ('aceptada', 'Aceptada por el cliente'), ('rechazada', 'Rechazada por el cliente')], default='pendiente', max_length=20)),
                ('periodo', models.CharField(blank=True, max_length=20)),
                ('score_al_generar', models.FloatField(default=0)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_propuestas', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='RankingHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=20)),
                ('score', models.FloatField(default=0)),
                ('variacion', models.FloatField(default=0)),
                ('metricas', models.JSONField(blank=True, default=dict)),
                ('generado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_historico', to='clientes.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'periodo')},
            },
        ),
    ]
