# Generated by Django 5.2.7 on 2026-02-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0004_ofertapropuesta_rankinghistorico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertapropuesta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('enviada', 'Enviada al cliente'), ('aceptada', 'Aceptada por el cliente'), ('rechazada', 'Rechazada por el cliente'), ('aplicada', 'Aplicada en pedido')], default='pendiente', max_length=20),
        ),
    ]
