# Generated by Django 5.2.7 on 2026-02-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0005_alter_ofertapropuesta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertapropuesta',
            name='tipo',
            field=models.CharField(choices=[('descuento', 'Descuento'), ('fidelizacion', 'Fidelización'), ('prioridad_stock', 'Prioridad en stock'), ('promocion', 'Promoción')], max_length=30),
        ),
    ]
