# Generated by Django 5.2.7 on 2026-02-07 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0006_alter_ofertapropuesta_tipo'),
        ('insumos', '0003_proyeccioninsumo'),
        ('pedidos', '0002_ordencompra'),
        ('proveedores', '0010_alter_proveedor_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaStockProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('disponible', 'Disponible'), ('parcial', 'Parcialmente disponible'), ('no', 'No disponible'), ('error', 'Error de consulta')], default='pendiente', max_length=20)),
                ('respuesta', models.JSONField(blank=True, default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.insumo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='CompraPropuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.PositiveIntegerField()),
                ('pesos_usados', models.JSONField(blank=True, default=dict)),
                ('motivo_trigger', models.CharField(choices=[('faltante_stock', 'Faltante de stock'), ('pedido_mayor_stock', 'Pedido supera stock'), ('stock_minimo_vencido', 'Stock mínimo vencido')], max_length=30)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('consultado', 'Consulta enviada'), ('respuesta_disponible', 'Respuesta disponible'), ('parcial', 'Disponibilidad parcial'), ('no_disponible', 'No disponible'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('modificada', 'Modificada')], default='pendiente', max_length=30)),
                ('decision', models.CharField(blank=True, max_length=20)),
                ('comentario_admin', models.TextField(blank=True)),
                ('feedback_pesos', models.JSONField(blank=True, default=dict)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('borrador_oc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.ordencompra')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.insumo')),
                ('proveedor_recomendado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedor')),
                ('consulta_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automatizacion.consultastockproveedor')),
            ],
        ),
    ]
