# Generated by Django 5.2.7 on 2026-02-10 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0007_consultastockproveedor_comprapropuesta'),
        ('clientes', '0009_cliente_fecha_ultima_actualizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('entregado', 'Entregado'), ('leido', 'Leído'), ('fallido', 'Fallido')], max_length=20)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('provider_id', models.CharField(blank=True, max_length=120)),
                ('detalle', models.TextField(blank=True)),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='automatizacion.ofertapropuesta')),
            ],
            options={
                'ordering': ('-actualizado',),
            },
        ),
    ]
