# Generated by Django 5.2.7 on 2026-02-10 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0008_mensajeoferta'),
        ('clientes', '0009_cliente_fecha_ultima_actualizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vista', 'Vista de oferta/listado'), ('click', 'Click en enlace/botón'), ('aceptar', 'Aceptó la oferta'), ('rechazar', 'Rechazó la oferta'), ('consulta', 'Realizó una consulta'), ('leido', 'Leyó el mensaje')], max_length=20)),
                ('canal', models.CharField(choices=[('web', 'Web'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='web', max_length=20)),
                ('detalle', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_cliente', to='clientes.cliente')),
                ('oferta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acciones_cliente', to='automatizacion.ofertapropuesta')),
            ],
            options={
                'ordering': ('-creado',),
            },
        ),
    ]
