# Generated by Django 5.2.7 on 2026-02-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0009_accioncliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertapropuesta',
            name='token_email',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
