# Generated by Django 6.0.2 on 2026-02-21 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0010_ofertapropuesta_token_email'),
        ('clientes', '0009_cliente_fecha_ultima_actualizacion_and_more'),
        ('productos', '0007_alter_producto_formula'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('enviada', models.BooleanField(default=False)),
                ('aceptada', models.BooleanField(default=False)),
                ('rechazada', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos_oferta', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ComboOfertaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatizacion.combooferta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='combooferta',
            name='productos',
            field=models.ManyToManyField(through='automatizacion.ComboOfertaProducto', to='productos.producto'),
        ),
    ]
