# Generated by Django 6.0.2 on 2026-03-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0012_ofertapropuesta_fecha_expiracion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertapropuesta',
            name='fecha_expiracion',
        ),
        migrations.AlterField(
            model_name='ofertapropuesta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('enviada', 'Enviada al cliente'), ('aceptada', 'Aceptada por el cliente'), ('rechazada', 'Rechazada por el cliente'), ('aplicada', 'Aplicada en pedido')], default='pendiente', max_length=20),
        ),
    ]
