# Generated by Django 6.0.2 on 2026-03-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0013_remove_ofertapropuesta_fecha_expiracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertapropuesta',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, help_text='Fecha límite para que el cliente responda. Se asigna automáticamente al crear.', null=True),
        ),
        migrations.AlterField(
            model_name='ofertapropuesta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('enviada', 'Enviada al cliente'), ('aceptada', 'Aceptada por el cliente'), ('rechazada', 'Rechazada por el cliente'), ('aplicada', 'Aplicada en pedido'), ('vencida', 'Vencida (no respondida a tiempo)')], default='pendiente', max_length=20),
        ),
    ]
