# Generated by Django 6.0.2 on 2026-03-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0014_ofertapropuesta_fecha_expiracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accioncliente',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='accioncliente',
            name='tipo',
            field=models.CharField(choices=[('vista', 'Vista de oferta/listado'), ('click', 'Click en enlace/botón'), ('aceptar', 'Aceptó la oferta'), ('rechazar', 'Rechazó la oferta'), ('consulta', 'Realizó una consulta'), ('leido', 'Leyó el mensaje')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='comprapropuesta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('consultado', 'Consulta enviada'), ('respuesta_disponible', 'Respuesta disponible'), ('parcial', 'Disponibilidad parcial'), ('no_disponible', 'No disponible'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('modificada', 'Modificada')], db_index=True, default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='ofertapropuesta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('enviada', 'Enviada al cliente'), ('aceptada', 'Aceptada por el cliente'), ('rechazada', 'Rechazada por el cliente'), ('aplicada', 'Aplicada en pedido'), ('vencida', 'Vencida (no respondida a tiempo)')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='ofertapropuesta',
            name='periodo',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
