# Generated by Django 6.0.2 on 2026-03-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0015_add_db_index_estado_periodo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertapropuesta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('enviada', 'Enviada al cliente'), ('aceptada', 'Aceptada por el cliente'), ('rechazada', 'Rechazada por el cliente'), ('aplicada', 'Aplicada en pedido'), ('vencida', 'Vencida (no respondida a tiempo)'), ('aceptada_sin_stock', 'Aceptada – sin stock para pedido automático')], db_index=True, default='pendiente', max_length=20),
        ),
    ]
