# Generated by Django 6.0.2 on 2026-03-15 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0016_alter_ofertapropuesta_estado'),
        ('insumos', '0010_add_sc_models'),
        ('proveedores', '0013_alter_proveedor_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de respuesta'), ('respondida', 'Respondida por proveedor'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida')], db_index=True, default='pendiente', max_length=20)),
                ('token', models.CharField(blank=True, max_length=64, unique=True)),
                ('comentario', models.TextField(blank=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cotizacion', to='proveedores.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario_respuesta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('disponible', models.BooleanField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.insumo')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='automatizacion.solicitudcotizacion')),
            ],
        ),
    ]
