# Generated by Django 6.0.2 on 2026-03-27 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0017_add_sc_models'),
        ('clientes', '0015_cliente_email_verificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cliente_inactivo', 'Cliente Inactivo'), ('presupuesto_recordatorio', 'Recordatorio Presupuesto'), ('oferta', 'Oferta Comercial')], max_length=30)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('email_enviado', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('abierto', 'Abierto'), ('clickeado', 'Clickeado'), ('respondido', 'Respondido')], default='enviado', max_length=20)),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('abierto_en', models.DateTimeField(blank=True, null=True)),
                ('clickeado_en', models.DateTimeField(blank=True, null=True)),
                ('respondido_en', models.DateTimeField(blank=True, null=True)),
                ('respuesta_texto', models.TextField(blank=True, default='')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tracking', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cliente_inactivo', 'Cliente Inactivo'), ('presupuesto_recordatorio', 'Recordatorio Presupuesto')], max_length=30)),
                ('email_origen', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='clientes.cliente')),
            ],
        ),
    ]
