# Generated by Django 6.0.2 on 2026-03-27 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0018_email_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertapropuesta',
            name='accion_aprobacion',
            field=models.CharField(blank=True, choices=[('aprobar', 'Aprobada'), ('rechazar', 'Rechazada'), ('enviar', 'Enviada')], max_length=20, null=True, verbose_name='Acción de validación'),
        ),
        migrations.AddField(
            model_name='ofertapropuesta',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación/rechazo'),
        ),
        migrations.AddField(
            model_name='ofertapropuesta',
            name='observacion_aprobacion',
            field=models.TextField(blank=True, default='', verbose_name='Observación de validación'),
        ),
        migrations.AlterField(
            model_name='ofertapropuesta',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofertas_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
