# Generated by Django 6.0.2 on 2026-04-11 13:52

import django.db.models.deletion
from django.db import migrations, models


def limpiar_borrador_oc_legacy(apps, schema_editor):
    """Pone en NULL los borrador_oc que apuntan a pedidos.OrdenCompra
    (modelo legacy) ya que no existen en compras.OrdenCompra."""
    CompraPropuesta = apps.get_model('automatizacion', 'CompraPropuesta')
    CompraPropuesta.objects.filter(borrador_oc__isnull=False).update(borrador_oc=None)


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0019_add_auditoria_aprobacion'),
        ('compras', '0013_comprapropuesta_borrador_oc_to_compras'),
    ]

    operations = [
        migrations.RunPython(limpiar_borrador_oc_legacy, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='comprapropuesta',
            name='borrador_oc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.ordencompra'),
        ),
    ]
