# Generated by Django 6.0.2 on 2026-02-24 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_multi_producto'),
        ('pedidos', '0003_ordenproduccion'),
    ]

    operations = [
    ]
