# Generated by Django 6.0.2 on 2026-02-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_merge_0002_multi_producto_0003_ordenproduccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapedido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
