# Generated by Django 6.0.2 on 2026-02-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_lineapedido_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
