# Generated by Django 6.0.2 on 2026-02-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_lineapedido_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='aplicar_iva',
            field=models.BooleanField(default=False, help_text='Si se aplica IVA 21% al pedido'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento aplicado al pedido', max_digits=5),
        ),
    ]
