# Generated by Django 6.0.2 on 2026-03-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_pedido_aplicar_iva_pedido_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='token_proveedor',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
