# Generated by Django 6.0.2 on 2026-04-11

from django.db import migrations


def consolidar_estado_pendiente(apps, schema_editor):
    """
    Elimina el estado 'pendiente' (minúscula, id=8) reasignando sus pedidos
    al estado canónico 'Pendiente' (id=1).
    """
    EstadoPedido = apps.get_model('pedidos', 'EstadoPedido')
    Pedido = apps.get_model('pedidos', 'Pedido')

    try:
        canonico = EstadoPedido.objects.get(nombre='Pendiente')
    except EstadoPedido.DoesNotExist:
        return  # nada que hacer

    duplicados = EstadoPedido.objects.filter(nombre='pendiente')
    for dup in duplicados:
        if dup.pk == canonico.pk:
            continue
        Pedido.objects.filter(estado=dup).update(estado=canonico)
        dup.delete()


def noop(apps, schema_editor):
    pass  # no reversible — no tiene sentido recrear el duplicado


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_pedido_eliminado'),
    ]

    operations = [
        migrations.RunPython(consolidar_estado_pendiente, noop),
    ]
