# Generated by Django 5.2.7 on 2025-11-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_proveedorparametro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedorparametro',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
