# Generated by Django 5.2.7 on 2025-12-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0006_alter_proveedorparametro_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='apellido',
            field=models.CharField(default='Ejemplo', max_length=100),
        ),
    ]
