# Generated by Django 4.2.25 on 2026-02-04 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0007_proveedor_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='rubro_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='proveedores.rubro'),
        ),
    ]
