# Generated by Django 5.2.7 on 2026-02-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0009_populate_rubro_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(db_column='nombreProveedor', max_length=100),
        ),
    ]
