# Generated by Django 5.2.7 on 2026-02-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0010_alter_proveedor_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='api_stock_url',
            field=models.URLField(blank=True, help_text='Endpoint para consulta de stock en proveedor real', null=True),
        ),
    ]
