# Generated by Django 6.0.2 on 2026-03-09 12:18

import proveedores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0011_proveedor_api_stock_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='telefono_e164',
            field=models.CharField(blank=True, help_text='Número celular en formato internacional, ej: +5493816123456. Necesario para enviar SMS y WhatsApp.', max_length=20, null=True, validators=[proveedores.models.validar_telefono_e164], verbose_name='Teléfono (E.164)'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número de WhatsApp en formato E.164. Dejar en blanco si coincide con Teléfono (E.164).', max_length=20, null=True, validators=[proveedores.models.validar_telefono_e164], verbose_name='WhatsApp'),
        ),
    ]
