# Generated by Django 6.0.2 on 2026-03-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0012_proveedor_telefono_e164_proveedor_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
