# Generated by Django 6.0.2 on 2026-04-11 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('proveedores', '0015_alter_proveedor_cuit_null_alter_proveedor_direccion_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='ciudad_fk',
            field=models.ForeignKey(blank=True, help_text='Referencia a la tabla de ciudades. Cuando está completo, tiene prioridad sobre el campo texto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores', to='geo.ciudad', verbose_name='Ciudad (normalizado)'),
        ),
    ]
