# Generated by Django 5.2.7 on 2025-11-01 18:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
        ('proveedores', '0003_add_missing_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='insumo',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='insumo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='insumos', to='proveedores.proveedor'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
