# Generated by Django 5.2.7 on 2025-12-05 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0002_insumo_cantidad_insumo_precio_unitario_and_more'),
        ('proveedores', '0006_alter_proveedorparametro_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyeccionInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=20)),
                ('cantidad_proyectada', models.PositiveIntegerField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('modificada', 'Modificada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('cantidad_validada', models.PositiveIntegerField(blank=True, null=True)),
                ('comentario_admin', models.TextField(blank=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.insumo')),
                ('proveedor_sugerido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedor')),
                ('proveedor_validado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyecciones_validadas', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Proyección de Insumo',
                'verbose_name_plural': 'Proyecciones de Insumos',
                'unique_together': {('insumo', 'periodo')},
            },
        ),
    ]
