# Generated by Django 5.2.7 on 2026-02-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0004_consumorealinsumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
