# Generated by Django 6.0.2 on 2026-03-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0006_insumo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(blank=True, default='unidad', max_length=20),
        ),
    ]
