# Generated by Django 6.0.2 on 2026-03-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0007_insumo_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='stock_minimo_manual',
            field=models.PositiveIntegerField(blank=True, help_text='Stock mínimo sugerido (cargado manualmente). Se usa cuando no hay historial de consumo.', null=True),
        ),
    ]
