# Generated by Django 6.0.2 on 2026-03-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0009_insumo_cantidad_compra_sugerida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumorealinsumo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proyeccioninsumo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
