# Generated by Django 6.0.2 on 2026-04-11 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0012_remove_insumo_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='stock_minimo_calculado',
            field=models.PositiveIntegerField(blank=True, help_text='Stock mínimo pre-calculado automáticamente (tarea programada). Evita queries N+1 en listados.', null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
