# Generated by Django 5.2.7 on 2025-11-21 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0001_initial'),
        ('productos', '0005_producto_gramos_por_pliego_producto_merma_papel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presupuesto',
            options={},
        ),
        migrations.CreateModel(
            name='PresupuestoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='detalles', to='presupuestos.presupuesto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
