# Generated by Django 5.2.7 on 2025-11-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0002_alter_presupuesto_options_presupuestodetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Razón social vinculada al presupuesto',
                                   max_length=150, null=True),
        ),
    ]
