# Generated by Django 6.0.2 on 2026-03-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0003_presupuesto_razon_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestodetalle',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento en %', max_digits=5),
        ),
        migrations.AddField(
            model_name='presupuestodetalle',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=21, help_text='IVA en %', max_digits=5),
        ),
    ]
