# Generated by Django 6.0.2 on 2026-03-07 22:25

import uuid
from django.db import migrations, models


def populate_tokens(apps, schema_editor):
    Presupuesto = apps.get_model('presupuestos', 'Presupuesto')
    for pres in Presupuesto.objects.filter(token__isnull=True):
        pres.token = uuid.uuid4()
        pres.save(update_fields=['token'])


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0004_presupuestodetalle_descuento_presupuestodetalle_iva'),
    ]

    operations = [
        # Paso 1: agregar respuesta_cliente con default
        migrations.AddField(
            model_name='presupuesto',
            name='respuesta_cliente',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10, verbose_name='Respuesta del cliente'),
        ),
        # Paso 2a: agregar token como nullable sin unique
        migrations.AddField(
            model_name='presupuesto',
            name='token',
            field=models.UUIDField(null=True, blank=True, editable=False),
        ),
        # Paso 2b: poblar con UUIDs únicos por fila
        migrations.RunPython(populate_tokens, migrations.RunPython.noop),
        # Paso 3: hacer el campo non-null, unique y con default para filas futuras
        migrations.AlterField(
            model_name='presupuesto',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
