# Generated by Django 5.2.7 on 2026-03-28 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_ordencompra_fecha_respuesta'),
        ('presupuestos', '0005_presupuesto_respuesta_cliente_presupuesto_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='pedido_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_origen', to='pedidos.pedido', verbose_name='Pedido generado'),
        ),
    ]
