# Generated by Django 6.0.2 on 2026-04-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0006_presupuesto_pedido_relacionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='recordatorio_enviado_fecha',
            field=models.DateField(blank=True, help_text='Se actualiza cada vez que se envía un recordatorio automático. Evita duplicados en el mismo día.', null=True, verbose_name='Fecha último recordatorio enviado'),
        ),
    ]
