# Generated by Django 6.0.2 on 2026-03-18 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatizacion', '0017_add_sc_models'),
        ('compras', '0001_crear_app_compras'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='solicitud_cotizacion',
            field=models.ForeignKey(blank=True, help_text='Solicitud de cotizacion confirmada que origino esta orden', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='automatizacion.solicitudcotizacion'),
        ),
    ]
