# Generated by Django 6.0.2 on 2026-03-19 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_vincular_solicitud_cotizacion'),
        ('insumos', '0010_add_sc_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste_positivo', 'Ajuste positivo'), ('ajuste_negativo', 'Ajuste negativo')], max_length=20)),
                ('origen', models.CharField(choices=[('remito', 'Remito de compra'), ('produccion', 'Orden de produccion'), ('ajuste', 'Ajuste manual'), ('automatico', 'Sistema automatico')], max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('stock_anterior', models.IntegerField(default=0)),
                ('stock_posterior', models.IntegerField(default=0)),
                ('referencia', models.CharField(blank=True, help_text='Ej: Remito R-0001, OC-0002', max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_stock', to='insumos.insumo')),
                ('remito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='compras.remito')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-creado_en'],
            },
        ),
    ]
