# Generated by Django 6.0.2 on 2026-03-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_movimiento_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='condicion_pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('15_dias', '15 días'), ('30_dias', '30 días'), ('60_dias', '60 días'), ('90_dias', '90 días')], default='contado', max_length=20),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_entrega',
            field=models.DateField(blank=True, help_text='Fecha estimada de entrega', null=True),
        ),
    ]
