# Generated by Django 5.2.7 on 2026-03-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_ordencompra_condicion_pago_ordencompra_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='enviada',
            field=models.BooleanField(default=False, help_text='Indica si la orden fue enviada al proveedor'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se envió la orden al proveedor', null=True),
        ),
    ]
