# Generated by Django 6.0.2 on 2026-04-06 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_historial_precio_insumo'),
        ('proveedores', '0015_alter_proveedor_cuit_null_alter_proveedor_direccion_blank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos argentinos (ARS)'), ('USD', 'Dólares (USD)')], default='ARS', max_length=3)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_retenciones', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_neto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('orden_compra', models.ForeignKey(blank=True, help_text='Orden de compra asociada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_pago', to='compras.ordencompra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_pago', to='proveedores.proveedor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_pago_creadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_aprobacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_pago_aprobadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Pago',
                'verbose_name_plural': 'Órdenes de Pago',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='FormaPagoOrdenPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('transferencia', 'Transferencia bancaria'), ('cheque', 'Cheque'), ('efectivo', 'Efectivo'), ('otro', 'Otro')], default='transferencia', max_length=20)),
                ('banco', models.CharField(blank=True, help_text='Banco emisor (transferencia/cheque)', max_length=100)),
                ('cbu', models.CharField(blank=True, help_text='CBU destino (transferencia)', max_length=22)),
                ('numero_cheque', models.CharField(blank=True, help_text='Número de cheque', max_length=50)),
                ('referencia', models.CharField(blank=True, help_text='Nº de transferencia, recibo, etc.', max_length=100)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14)),
                ('orden_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pago', to='compras.ordenpago')),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
            },
        ),
        migrations.CreateModel(
            name='ComprobanteOrdenPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('factura_a', 'Factura A'), ('factura_b', 'Factura B'), ('factura_c', 'Factura C'), ('nota_credito', 'Nota de Crédito'), ('nota_debito', 'Nota de Débito'), ('recibo', 'Recibo')], default='factura_a', max_length=20)),
                ('numero', models.CharField(help_text='Ej: 0001-00012345', max_length=50)),
                ('fecha', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('orden_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='compras.ordenpago')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
            },
        ),
        migrations.CreateModel(
            name='RetencionOrdenPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('iva', 'Retención IVA'), ('ganancias', 'Retención Ganancias'), ('ingresos_brutos', 'Ingresos Brutos'), ('suss', 'SUSS'), ('otro', 'Otro')], default='iva', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14)),
                ('orden_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retenciones', to='compras.ordenpago')),
            ],
            options={
                'verbose_name': 'Retención',
                'verbose_name_plural': 'Retenciones',
            },
        ),
    ]
