# Generated by Django 6.0.2 on 2026-04-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_remito_anulado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='token_proveedor',
            field=models.CharField(blank=True, help_text='Token único enviado al proveedor para confirmar/rechazar sin login', max_length=64, unique=True),
        ),
    ]
