# Generated by Django 5.2.7 on 2025-11-12 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0002_insumo_cantidad_insumo_precio_unitario_and_more'),
        ('productos', '0003_producto_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_por_unidad', models.DecimalField(decimal_places=3,
                 help_text='Cantidad requerida por unidad de producto', max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='insumos.insumo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='receta', to='productos.producto')),
            ],
            options={
                'unique_together': {('producto', 'insumo')},
            },
        ),
    ]
