# Generated by Django 5.2.7 on 2025-11-13 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0002_insumo_cantidad_insumo_precio_unitario_and_more'),
        ('productos', '0004_productoinsumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='gramos_por_pliego',
            field=models.DecimalField(blank=True, decimal_places=2,
                                      help_text='Gramos de tinta por pliego', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='merma_papel',
            field=models.DecimalField(blank=True, decimal_places=4,
                                      help_text='Merma de papel (ej: 0.10 para 10%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='merma_tinta',
            field=models.DecimalField(blank=True, decimal_places=4,
                                      help_text='Merma de tinta (ej: 0.05 para 5%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='papel_insumo',
            field=models.ForeignKey(blank=True, help_text='Insumo de papel a descontar (pliegos)', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, related_name='productos_papel', to='insumos.insumo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tinta_insumo',
            field=models.ForeignKey(blank=True, help_text='Insumo de tinta a descontar (gramos)', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, related_name='productos_tinta', to='insumos.insumo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidades_por_pliego',
            field=models.PositiveIntegerField(blank=True, help_text='Unidades impresas por pliego', null=True),
        ),
    ]
