# Generated by Django 5.2.7 on 2025-12-14 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_alter_recetaproducto_unique_together_and_more'),
        ('productos', '0005_producto_gramos_por_pliego_producto_merma_papel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='gramos_por_pliego',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='merma_papel',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='merma_tinta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='papel_insumo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidades_por_pliego',
        ),
        migrations.AddField(
            model_name='producto',
            name='formula',
            field=models.ForeignKey(default=django.utils.timezone.now, help_text='Fórmula para calcular los insumos de este producto', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='configuracion.formula'),
            preserve_default=False,
        ),
    ]
