# Generated by Django 5.2.7 on 2026-02-15 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0008_alter_recetaproducto_insumos'),
        ('productos', '0006_remove_producto_gramos_por_pliego_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='formula',
            field=models.ForeignKey(default=1, help_text='Fórmula para calcular los insumos de este producto', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='configuracion.formula'),
            preserve_default=False,
        ),
    ]
