# Generated by Django 6.0.2 on 2026-03-03 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0006_insumo_tipo'),
        ('productos', '0007_alter_producto_formula'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R', models.DecimalField(decimal_places=2, default=1, help_text='Rendimiento: unidades por pliego', max_digits=8)),
                ('M', models.DecimalField(decimal_places=4, default=0.05, help_text='Merma (ej: 0.05 = 5%)', max_digits=5)),
                ('C', models.PositiveSmallIntegerField(default=4, help_text='Cantidad de colores (1=B/N, 4=CMYK)')),
                ('F', models.PositiveSmallIntegerField(default=1, help_text='Caras impresas (1 o 2)')),
                ('Formas', models.PositiveSmallIntegerField(default=1, help_text='Cantidad de formas de impresion')),
                ('ancho_pliego_cm', models.DecimalField(decimal_places=2, default=70, max_digits=6)),
                ('alto_pliego_cm', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('gramaje', models.DecimalField(decimal_places=2, default=130, help_text='Gramaje del papel en g/m2', max_digits=6)),
                ('At', models.DecimalField(decimal_places=4, default=0.06, help_text='Area impresa por unidad en m2', max_digits=8)),
                ('Ct', models.DecimalField(decimal_places=2, default=1.5, help_text='Consumo promedio gr/m2 por color', max_digits=6)),
                ('tiene_barniz', models.BooleanField(default=False)),
                ('Cb', models.DecimalField(decimal_places=2, default=0, help_text='Consumo gr/m2 barniz', max_digits=6)),
                ('tiene_laminado', models.BooleanField(default=False)),
                ('Plam', models.DecimalField(decimal_places=4, default=0, help_text='Precio por m2 laminado', max_digits=8)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_tecnicos', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Parametros Tecnicos del Producto',
            },
        ),
        migrations.CreateModel(
            name='RecetaDinamica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receta_dinamica', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Receta Dinamica',
                'verbose_name_plural': 'Recetas Dinamicas',
            },
        ),
        migrations.CreateModel(
            name='LineaReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('papel', 'Papel'), ('tinta', 'Tinta'), ('plancha', 'Plancha'), ('barniz', 'Barniz'), ('laminado', 'Laminado'), ('otro', 'Otro')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_receta', to='insumos.insumo')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='productos.recetadinamica')),
            ],
            options={
                'verbose_name': 'Linea de Receta',
                'verbose_name_plural': 'Lineas de Receta',
                'ordering': ['orden', 'tipo'],
            },
        ),
    ]
