# Generated by Django 6.0.2 on 2026-03-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_parametroproducto_recetadinamica_lineareceta'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoinsumo',
            name='es_costo_fijo',
            field=models.BooleanField(default=False, help_text='Si es True, la cantidad es fija por trabajo (no se multiplica por la cantidad pedida). Usar para planchas, fotolitos y similares.'),
        ),
    ]
