# Generated by Django 6.0.2 on 2026-04-02 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0008_alter_recetaproducto_insumos'),
        ('productos', '0009_productoinsumo_es_costo_fijo'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE productos_producto SET unidadMedida_id = NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidadMedida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracion.unidaddemedida'),
        ),
    ]
