# Generated by Django 5.2.7 on 2025-11-08 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
            },
        ),
        migrations.CreateModel(
            name='GrupoParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Grupo de Parámetros',
                'verbose_name_plural': 'Grupos de Parámetros',
            },
        ),
        migrations.CreateModel(
            name='ListaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Identificador del listado, ej: LISTA_PRODUCTOS', max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('page_size', models.PositiveIntegerField(default=10)),
                ('max_page_size', models.PositiveIntegerField(default=200)),
                ('orden_default', models.CharField(blank=True,
                 help_text="Campo(s) por defecto para orden, ej: '-creado'", max_length=120)),
                ('columnas_visibles', models.TextField(blank=True, help_text='Lista CSV de columnas activas')),
                ('activo', models.BooleanField(default=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Lista',
                'verbose_name_plural': 'Configuraciones de Listas',
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Clave única del parámetro', max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('str', 'Cadena'), ('int', 'Entero'), ('float',
                 'Decimal'), ('bool', 'Booleano'), ('json', 'JSON')], default='str', max_length=10)),
                ('valor', models.TextField(help_text='Valor almacenado en formato texto')),
                ('activo', models.BooleanField(default=True)),
                ('editable', models.BooleanField(default=True, help_text='Si puede modificarse vía panel')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='parametros', to='configuracion.grupoparametro')),
            ],
            options={
                'verbose_name': 'Parámetro',
                'verbose_name_plural': 'Parámetros',
                'ordering': ['codigo'],
            },
        ),
    ]
