# Generated by Django 5.2.7 on 2025-11-15 14:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_formula_formulahistorial'),
        ('insumos', '0002_insumo_cantidad_insumo_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='insumo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='formulas', to='insumos.insumo'),
            preserve_default=False,
        ),
    ]
