# Generated by Django 5.2.7 on 2025-11-18 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_formula_insumo'),
        ('insumos', '0002_insumo_cantidad_insumo_precio_unitario_and_more'),
        ('productos', '0005_producto_gramos_por_pliego_producto_merma_papel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='recetas', to='configuracion.formula')),
                ('insumos', models.ManyToManyField(related_name='recetas', to='insumos.insumo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='recetas', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Receta de Producto',
                'verbose_name_plural': 'Recetas de Productos',
                'unique_together': {('producto', 'formula')},
            },
        ),
    ]
