# Generated by Django 4.2.25 on 2025-11-23 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_unidaddemedida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetaproducto',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='recetas', to='configuracion.formula'),
        ),
    ]
