# Generated by Django 5.2.7 on 2025-11-30 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_alter_recetaproducto_formula'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recetaproducto',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='recetaproducto',
            name='formula',
        ),
    ]
