# Generated by Django 5.2.7 on 2026-02-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0007_alter_recetaproducto_unique_together_and_more'),
        ('insumos', '0005_insumo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetaproducto',
            name='insumos',
            field=models.ManyToManyField(to='insumos.insumo'),
        ),
    ]
